# Use the official Apache HTTP Server image
FROM httpd:2.4

# Copy all files from the current directory to the default Apache document root
COPY . /usr/local/apache2/htdocs/

# Expose port 80 (default Apache port)
EXPOSE 8080
